---
title: "Derogations and Democratic Backsliding: Exploring the Pandemic's Effects on Civic Spaces"
author:
- name: Suparna Chaudhry
  affiliation: Lewis & Clark College
  email: schaudhry@lclark.edu
  url: http://www.suparnachaudhry.com/
- name: Andrew Heiss
  affiliation: Georgia State University
  email: aheiss@gsu.edu
  url: https://www.andrewheiss.com/
date: March 21, 2021
published: This is an early draft of a working paper.
git-repo: https://example.com
abstract: >-
  In an effort to combat the COVID-19 pandemic, most governments have imposed restrictions on movement, association, and other civic freedoms in the interest of public health. In many cases, such as New Zealand, these emergency measures have been temporary and respect for human rights has returned to normal. In many other instances, however, governments have used these restrictions to suppress opposition and more permanently restrict civic space. Systematically measuring the consequences of COVID restrictions, however, is a difficult task. We will examine two possible quantitative measures of the relationship between of COVID restrictions and civil society space. First, we will use the Variety of Democracy project's newly released Pandemic Violations of Democratic Standards Index to explore if and how civil society restrictions predict pandemic backsliding. Second, while many countries sign international human rights treaties that ostensibly bind states to respect rights, several treaties allow for emergency derogations from these obligations. We will tabulate formal human rights treaty derogations due to the pandemic and explore whether these emergency measures led to lasting declines in associational and human rights. We hope that our exploration of these two measures will provide rich data-based descriptions of the relationship between COVID restrictions and civic space that will allow for more causal work in the future.
reference-section-title: References
---

In an effort to combat the COVID-19 pandemic, governments across the world have imposed restrictions on freedom of movement, association, assembly and other civic freedoms in the interest of public health. Many of these states have done so by declaring states of emergency and formally derogating from their international treaty obligations. Yet, far more countries have adopted emergency measures and restricted individual liberties than have derogated from human rights treaties. Even within states that have formally derogated, some states' responses have been temporary and proportionate as advised by the United Nations Office of the High Commissioner of Human Rights [source: https://www.ohchr.org/Documents/Events/EmergencyMeasures_COVID19.pdf] - while others have used these measures to suppress opposition and more permanently restrict civic space. During the COVID-19 pandemic, how many countries have formally derogated from their human rights treaty obligations and how does the nature of measures implemented during this period differ across countries? In the long-term, we aim to use our rich data-based description of the relationship between pandemic restrictions and civic space to examine whether these emergency measures led to lasting declines in associational and human rights, furthering the phenomenon of closing civic space.

Studying state compliance with the international human rights treaty obligations as well as the (unintended) effects of derogations is important, especially given the ongoing prior phenomenon of closing civic space. Even prior to the pandemic, since 2013, 91 countries had proposed or enacted 244 measures restricting civil society [source: https://www.icnl.org/our-work/global-programs/the-civic-space-initiative].  In Human Rights Watch’s 2016 World Report, Executive Director Kenneth Roth argued that civil society was under more aggressive attack than at any time in recent memory. ANDREW: DO YOU WANT TO INCLUDE SOME SUMMARY FIGURES FROM OUR DATA/CLOSING SPACE CHAPTER??

Once the pandemic began, according to the International Center for Not-for-Profit Law (ICNL) 107 countries declared emergency, 56 implemented measures affecting freedom of expression and even more -- 139 countries implemented measures affecting freedom of assembly [source: https://www.icnl.org/covid19tracker/]. Many others have erected new barriers to public information, prevented NGOs from delivering services. In seeking to target disinformation, many countries have penalized dissent and securitized the response to the pandemic, using it as a justification for reducing civic freedoms. Other governments have used pandemic restrictions as an excuse for delaying elections [https://www.ifes.org/publications/global-impact-covid-19-elections] or for denying arrested individuals adequate legal representation in judicial proceedings [https://www.unodc.org/documents/Advocacy-Section/Ensuring_Access_to_Justice_in_the_Context_of_COVID-191.pdf].

While some countries have implemented these measures without formally derogating from international human rights treaties, otherwise have esssentially violated their treaty commitments. But even among countries that formally derogate, it is worth documenting measures as many countries have renewed their derogations -- leading to concerns about serial derogators and its potential consequences on measures that are neither proportional nor temporary.

Using original data on derogations to the International Covenant on Civil and Political Rights (ICCPR) during the pandemic as well as data on measures implemented during Covid-19 from PanDem by V-DEM, we find 1) HOW MANY COUNTRIES ACTUALLY DEROGATED 2) Countries that implement emergency measures while legally derogating from their treaty commitments ARE DOING WHAT/CONFIRM less likely to violate non-derogable rights during the pandemic ONCE WE HAVE FULL DATA 3) ANY OTHER FINDINGS


# Derogations

Derogations in international law authorize states to temporarily escape their international treaty commitments during times of crises (Hafner-Burton et al 2011, 647). These derogations are especially important from a human rights perspective, since they are triggered during crises, when individual liberies are under serious threat (677). By declaring a state of public emergency and formally derogating, states acknowledge that these measures are temporary, necessary, and proportional to the interest at stake, with an aim to restore normalcy as soon as possible. Without this option, states facing emergencies may outrightly violate their treaty commitments under international law. Further, they may also illegally violate non-derogable rights such as right to life, freedom from torture and slavery. 

While the most frequent derogators are stable democracies and countries where domestic courts can exercise strong oversight of the executive and hold them responsible for breaches of human rights agreements, derogations, especially in the context of a long-lasting event such as the pandemic are more concerning because of the tendency of some countries to turn into ``serial derogators." These countries generally derogate ``without providing information about rights restrictions and in multiple consecutive years." (Hafner-Burton et al 675) These patterns are typically encountered in countries where the judiciary is weak and voters cannot easily remove leaders from office. 

## Derogations during the pandemic

The exceptional circumstances brought on by the global pandemic has led to numerous extensive derogations. International human rights treaties typically lay out circumstances during which derogations may take place -- for the European Convention on Human Rights, derogations can apply `in terms of war or other public emergency threatening the life of the nation,' for the American Convention on Human Rights, a `time of war, public danger, or other emergency that threatens the independence or security of a state.' [source:https://www.ohchr.org/Documents/Publications/training9chapter16en.pdf] In the current version of the paper, however, we focus on derogations (and violations) from the International Convenant on Civil and Political Rights, arguably among the most significant and extensive treaties in the international human rights regime. 

The ICCPR was adopted by the United Nations’ (UN) General Assembly on December 19, 1966 and came into force on March 23, 1976. Its purpose was to “recognize the inherent dignity of each individual and [to] undertake to promote conditions within states to allow the enjoyment of civil and political rights.” The ICCPR allows the suspension or derogation of certain civil and political rights only under specific situations of emergency that "threaten the life of the nation." [source: https://www.ohchr.org/en/professionalinterest/pages/ccpr.aspx]

Due to the number of states using a variety of measures to curb civil and political rights, the UN Human Rights Office of the High Commissioner published guidance on emergency measures on 27 April 2020, noting that emergency measures must meet the criteria of legality, necessity, proportionality, and non-discrimination. Further, states of emergency are specifically regulated under human rights law and that "states should take measures to prevent human rights violations and abuses associated with the state of emergency perpetrated by state and non-state actors." [source: https://www.ohchr.org/Documents/Events/EmergencyMeasures_COVID19.pdf] It concluded with a reminder of the necessity of democratic practices -- including transparency, right to information, media freedom, rule of law and allowing dissent. 

However, since these above democratic freedoms and practices have been under assault owing to closing civic space and more generally, trends in democratic backsliding, it raises concerns that many states may be using emergency measures intended to deal with the pandemic as a way to permanently suppress civic space. 


# Data


## Descriptive


# Exploratory case analysis
As shown above, numerous countries that ratified the ICCPR derogated during the pandemic -- many of these countries implemented measures going far beyond the recommended legal, necessary, temporary and proportional nature. These resulting measures, and in the case of countries violating their international treaty commitments without appropriate derogations, there can be numerous consequences for civic space. In the long-term, while we assess this above relationship through the use of systematic data through quantitative means, below, we conduct some exploratory case illustrations. These cases show the range in variation in how states have responded to their international legal commitments - some have derogated as intended, some have officially derogated from their treaty commitments but their measures are arguably not considered as temporary and proportional as necessary. Yet, other countries have avoid derogating completely, thus violating their treaty commitments. 


## Derogated as intended


## Officially derogated but measures not temporary and proportional
Armenia reported its first COVID-19 case on March 1st, 2020. As the number of cases rose, the government proclaimed a state of emergency on March 16 of the same year citing Article 3 of the Armenian Constitution which requires “the State to take measures for the protection of the life and health of individuals” [Government of the Republic of Armenia]. Subsequently, Armenia also officially derogated from Article 9, 12 and 21 of the ICCPR, as well as Article 11 of the ECHR March 20, 2020 [FOOTNOTE WHAT THESE ARE]. For both derogations, Armenia extended its original 30 day state of emergency expected to end on April 14th, 2020 another 30 days to May 14th, 2020. They issued five total 30 day extensions on the state of emergency and subsequent derogations. Armenia’s state of emergency finally concluded on September 11th, 2020. It issued a notice of withdrawal of derogation from the ECHR on September 16th, 2020 [“Reservations and Declarations for Treaty No.005 - Convention for the Protection of Human Rights and Fundamental Freedoms.” Treaty Office, Council of Europe.].

Some of Armenia's derogations have had a negative impact on vulnerable populations even though they were intended to be non-discriminatory, as per guidance from the UN’s Human Rights Office of the High Commissioner (OHCHR). Its decision to derogate from Article 9 of ICCPR was neither a necessary nor a proportionate measure to aid them in halting the public health crisis caused by the pandemic as it caused further issues to public health and to the judicial system.  One of the populations that was particularly affected by this derogation were detainees. Article 9 of the ICCPR which gives the right to all detainees to a fair and timely trial. By derogating from this article, the Armenian government disproportionately targeted detainees in comparison to the rest of the population. As the Armenian government grappled with the rapidly spreading pandemic they tried to slow its spread through the judicial system by halting court proceedings. This resulted in overcrowding of detaining facilities which posed a risk to the health of detained individuals and to public health [Mamulyan, Araks, and Narek Aleksanyan. “Armenia's Courts and the Coronavirus: Overcoming the Challenges.” Hetq, Hetq Investigative Journalism, 31 Dec. 2020, hetq.am/en/article/125964.]. The problem was exacerbated by the government’s decision to prolong its derogation multiple times.

Victims of domestic abuse were also unintendedly harmed by the government’s decision to proclaim the state of emergency and derogate from Article 21 of ICCPR and Article 11 of ECHR. As these proclamations meant that people could not leave their houses after a certain time and could not congregate with others, many women found themselves trapped in their homes under constant surveillance of their abusers. The police department recorded no increase in reports of domestic abuse, however, the Ombudsperson’s Office and various NGOs received an influx of reports after some measures had been lifted [Mkrtchyan, Gayane. “Armenia: Activists Call for More Action on Abuse.” Institute for War and Peace Reporting, 4 June 2020, iwpr.net/global-voices/armenia-activists-call-more-action-abuse.]


## C: Emergency declared but no formal derogation

Egypt has been under a constant state of emergency since April 1st 2017. Since then, the state of emergency has been extended 12 times for additional periods of 3 months, including May 2020, October 2020, and January 2021 [source: “The Global State of DEMOCRACY INDICES.” https://www.idea.int/gsod-indices//#/indices/countries-regions-profile?rsc=%5B651%5D&covid19=1.]. While the Egyptian government has formally declared a state of emergency, there has been no formal filing for derogations from the treaties that Egypt has ratified [Centre for Civil and Political Rights, “States of Emergencies in Response to the COVID-19 Pandemic.” https://datastudio.google.com/u/0/reporting/1sHT8quopdfavCvSDk7t-zvqKIS0Ljiu0/page/dHMKB ]. Egypt ratified the ICCPR in 1982 and since the beginning of the pandemic, the governments has implemented numerous measures that violate the rights outlined in ICCPR.

A large part of these restrictions focus on limiting freedom of movement and freedom of speech. There have been bans of all gatherings and more stringent regulations for the media to follow in an effort to block false information. These media regulations has to led to many news websites and social media accounts being blocked for “spreading rumors” about the pandemic. In February 2020,  at least ten doctors and six journalists were arrested for false information or for criticism of the government’s response [https://apnews.com/article/cf9528ebff1d5dd7e3b95d467d7e9418]. However, the government has not specified which information is false [https://rsf.org/en/news/egypt-blocks-online-fake-news-about-coronavirus]. 

In restricting freedom of movement, in addition to closing all shops and flights, the government also institued a curfew with fines of up to 4,000 Egyptian pounds ($255USD) or prison for violators [Mahmoud Mourad and Aidan Lewis, “Egypt declares two-week curfew to counter coronavirus.” Reuters, 24 March 2020, https://www.reuters.com]. As of September, the government had relaxed some of the restrictions on movement and gatherings, but had not lifted the restrictions on media and information [ICNL, “COVID-19 Civic Freedom Tracker: Egypt.”]. This is part of a longer trend -- since 2018, Egyptian law allows authorities to censor “online media outlets, websites, and personal social media accounts with more than 5,000 followers.”[https://rsf.org/en/news/egypt-blocks-online-fake-news-about-coronavirus].


## D: No emergency, no formal derogation

To illustrate the impact of pandemic restrictions and its impact on civic space without a formal declaration of emergency and consequent notice of derogation, we look at the case of India. According to article 352 of India’s constitution, India is only allowed to declare a state of emergency to when their territory itself is threatened “by war or external aggression or armed rebellion.” [source: Roser, Max, Hannah Ritchie, Esteban Ortiz-Ospina, and Joe Hasell. 2020. “Coronavirus Pandemic (COVID-19).” Our World in Data, May. https://ourworldindata.org/coronavirus/country/india.] Despite having a total of over 11.5 million cases since the start of the pandemic and the implementation of measures to protect a sixth of the world’s population, India has not derogated from any of their treaties and instead has simply violated them. Without officially derogating, there is an absence of sunset clauses that typically ensure that there is an end to the measures a country implements during an emergency.  Many of the measures against COVID-19 that have been implemented seem to disregard many fundamental human rights that should have been protected even in a state of emergency. This is vital because India is a party to both the International Covenant on Economic, Social and Cultural Rights (CESCR) and the ICCPR. 

When India went into lockdown in March 2020, the government only provided a four hour notice which left many scrambling in confusion and desperation. This four hour notice goes against ICCPR’s Article 19 which guarantees the right to seek and receive information, which includes early warnings of national measures like the lockdown. Not only is this a violation of the ICCPR, the CESCR General Comment No. 14 says that “access to information concerning the main health problems in the community, including methods of preventing and controlling them” is also a guaranteed right [source: https://www.amnestyusa.org/press-releases/responses-to-covid-19-and-states-human-rights-obligations-preliminary-observations/]. The lack of notice stranded a large numbers of migrant workers in cities, far from their homes in rural areas, with no transportation. Many of these workers died while trying to walk hundreds of miles back to their villages [source: https://www.washingtonpost.com/politics/2020/03/30/how-india-plans-put-13-billion-people-coronavirus-lockdown/].

Other measures have disproportionately impacted journalists' ability to work. For example, the Maharashtra government, “prohibits organizations or individuals from publicizing information about the coronavirus without ascertaining prior clearance from relevant government health authorities.” [source: http://www.icnl.org/covid19tracker/.] While these kinds of measures may have intended to prevent the spread of misinformation, they have been used to suppress journalists and activists. The government has also used pandemic restrictions to arbitrarily arrest and detian opponents to the regime -- including those protesting the government and its Hindu nationalist policies [https://www.nytimes.com/2020/07/19/world/asia/india-activists-arrests-riots-coronavirus.html?referringSource=articleShare&mc_cid=ffcb9e81ea&mc_eid=53f475e67b]. Subsequent to their arrest, detainees have had limited access to legal counsel, which has delayed their bails and led to their continued detention [https://www.hrw.org/news/2020/06/15/india-end-bias-prosecuting-delhi-violence]. 

Many measures have also violated the right to privacy which is not only protected by both ICCPR and ICESCR [footnote: article 17 of the ICCPR. “No one shall be subjected to arbitrary or unlawful interference with his privacy, family, home or correspondence, nor to unlawful attacks on his honour and reputation.”]; it is even recognised as a fundamental right under Article 21 of the Indian Constitution. Concerns over enhanced surveillance techniques have also risen also due to a lack of security measures in sensitive information pertaining to the pandemic. There have been multiple leaks of personal information of infected peoples which has led to discrimination and even assault. These measures have led to some cases of Muslims being assaulted, harassed and denied medical attention or spikes in caste-based discrimination and violence during the pandemic [source: https://www.washingtonpost.com/opinions/2020/04/06/islamophobia-taints-indias-response-coronavirus/]. 

Overall, India can not declare a state of emergency due to the fact that the Constitution only allows for a state of emergency to be declared under a physical threat to their territory. Since it can not declare a state of emergency, the government can not officially submit to the UN their intent to derogate from their treaties. Because the state can not derogate, it is simply violating its treaty commitments. In putting its entire population under lockdown with little warning, many women suffered disproportionately and other minority groups such as Muslims recieved backlash and discrimination both of which are non-derogable offense to the ICCPR under article 4. The lockdown also violated rights such as the right to information, the right to free movement, the right to privacy, and personal safety and integrity. 

# Next steps
